// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXEU36pWpIOFy0AdxJP1kBfM6oI2Hmx9o',
    appId: '1:472178615408:web:7b197c1f26df6af3f380b5',
    messagingSenderId: '472178615408',
    projectId: 'eventmanagementapp-bf192',
    authDomain: 'eventmanagementapp-bf192.firebaseapp.com',
    storageBucket: 'eventmanagementapp-bf192.firebasestorage.app',
    measurementId: 'G-SZY5ZT5FBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1mfMmNMJgk2dQaNyer_LtQo9AswvMzE0',
    appId: '1:472178615408:android:029b28b791f70028f380b5',
    messagingSenderId: '472178615408',
    projectId: 'eventmanagementapp-bf192',
    storageBucket: 'eventmanagementapp-bf192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFWcrxafRT8EBxNRRKTDI6eAtiJM8V3w',
    appId: '1:472178615408:ios:d0c8fe8d4dde9e05f380b5',
    messagingSenderId: '472178615408',
    projectId: 'eventmanagementapp-bf192',
    storageBucket: 'eventmanagementapp-bf192.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFWcrxafRT8EBxNRRKTDI6eAtiJM8V3w',
    appId: '1:472178615408:ios:d0c8fe8d4dde9e05f380b5',
    messagingSenderId: '472178615408',
    projectId: 'eventmanagementapp-bf192',
    storageBucket: 'eventmanagementapp-bf192.firebasestorage.app',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXEU36pWpIOFy0AdxJP1kBfM6oI2Hmx9o',
    appId: '1:472178615408:web:58cc3da86acfacb5f380b5',
    messagingSenderId: '472178615408',
    projectId: 'eventmanagementapp-bf192',
    authDomain: 'eventmanagementapp-bf192.firebaseapp.com',
    storageBucket: 'eventmanagementapp-bf192.firebasestorage.app',
    measurementId: 'G-G8RTZWF1F7',
  );
}
